config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable
    post :subscribe, on: :member
    delete :unsubscribe, on: :member
  end

  resource :search, only: :show

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers, shallow: true
      end
    end
  end

  root to: "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :subscriptions

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_commit :calculate_reputation, :on => :create

  scope :created_recently, -> { where('created_at >= ?', 1.day.ago) }

  def created_before
    @numbers_of_day = (Time.now - self.created_at).to_f/60/60/24
    if @numbers_of_day >= 1
      "опубликовано около #{ @numbers_of_day.to_i } дней назад"
    else
      "опубликовано менее #{ ((@numbers_of_day - @numbers_of_day.to_i) * 24).to_i + 1 } часов назад"
    end
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    @question = Question.find(params[:id])
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: @question.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
  before_action :authenticate_user!, except: [:index, :show]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.attachments.new
    gon.question_id = @question.id
  end

  def new
    @question = Question.new
    @question.attachments.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
      ActionCable.server.broadcast "/questions", question: @question
    else
      render :new
    end
  end

  def update
    if @question.user == current_user
      @question.update(question_params)
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'You question successfully deleted'
  end

  def subscribe
    @question.subscriptions.create(user: current_user) unless find_subscription
    redirect_to @question
  end

  def unsubscribe
    find_subscription.destroy if find_subscription
    redirect_to @question
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end

  def find_subscription
    @subscription = current_user.subscriptions.find_by(question_id: @question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.erb
<% @question.answers.each do |answer| %>
  <% if answer.persisted? %>
    <% cache answer do %>
      <div class="answer" id="answer-<%= answer.id %>">
        <p>
          <%= answer.body %>
        </p>
        <ul>
          <% answer.attachments.each do |attachment| %>
            <li>
              <%= link_to attachment.file.filename, attachment.file.url %>
            </li>
          <% end %>
        </ul>
        <%= link_to 'Edit', '', class: 'edit_answer_link', data: { answer_id: answer.id } if current_user == answer.user %>
        <%= form_with(model: answer, html: { id: "edit_answer_#{ answer.id }", style: "display: none" } ) do |form| %>
          <%= form.label :body, 'Answer' %>
          <div class="answer-errors">
          </div>
          <div>
            <%= form.text_area :body %>
          </div>
          <div>
            <%= link_to_add_association 'Add file', form, :attachments, partial: 'questions/attachment_fields' %>
          </div>
          <%= form.submit 'Save' %>
        <% end %>
        <div class="comments">
          <%= render 'comments/comments', parent: answer %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/questions/_attachment_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :file %>
    <div>
      <%= f.file_field :file %>
    </div>
  </div>
</div>

app/views/questions/_form.html.erb
<% hidden = false unless local_assigns[:hidden] %>
<%= form_with(model: @question, html: { style: "display: #{ hidden ? 'none' : 'block' }"}, class: 'edit_question' ) do |form| %>
  <div class="row">
    <div class="col-12">
      <%= form.label :title %>
      <div>
        <%= form.text_field :title, maxlength: 80 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form.label :body %>
      <div>
        <%= form.text_area :body, cols: 83, rows: 10 %>
      </div>
      <div>
        <%= link_to_add_association 'Add file', form, :attachments, partial: 'questions/attachment_fields' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="row">
  <div class="col-4">
    <b>
      <%= @question.title %>
    </b>
  </div>
  <% if signed_in? %>
    <div class="col-8">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <% if current_user.subscribed?(@question) %>
            <%= link_to 'Unsubscribe', unsubscribe_question_path, method: :delete,
                        data: { confirm: 'Do you want to unsubscribe?' }, class: "nav-link active btn btn-primary" %>
          <% else %>
            <%= link_to 'Subscribe', subscribe_question_path, method: :post,
                        data: { confirm: 'Do you want to subscribe?' }, class: "nav-link active btn btn-primary" %>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
</div>
<hr>
<div class="row">
  <div class="col-12">
    <p>
      <%= @question.body %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <ul>
      <% @question.attachments.each do |attachment| %>
        <li>
          <%= link_to attachment.file.filename, attachment.file.url %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<p class="question_errors">
</p>
<%= render 'form', hidden: true %>
<div class="row">
  <div class="col-12">
    <%= link_to 'Edit', edit_question_path(@question), class: 'edit_question_link' if @question.user == current_user %>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= link_to 'Delete', @question, method: :delete, data: { confirm: 'Are you sure?' } if @question.user == current_user %>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-4">
    <h2>
      Главные вопросы
    </h2>
  </div>
  <div class="col-8">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to 'Ask question', new_question_path, class: "nav-link active btn btn-primary" %>
      </li>
    </ul>
  </div>
</div>
<br>
<div class="row">
  <div class="col-12">
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to 'Интересные', '', class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Рекомендуемые', '', class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Горячие', '', class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Неделя', '', class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Месяц', '', class: "nav-link disabled" %>
      </li>
    </ul>
  </div>
</div>
<hr>
<div class="questions">
  <% @questions.each do |question| %>
    <div class="row">
      <div class="col-4">
        <nav aria-label="...">
          <ul class="pagination pagination-lg">
            <li class="page-item">
              <%= link_to question_path(question), class: "page-link", style: "font-size: 10px; text-align: center;" do %>
                <span>1</span>
                <br>
                <span>votes</span>
              <% end %>
            </li>
            <li class="page-item">
              <%= link_to question_path(question), class: "page-link", style: "font-size: 10px; text-align: center;" do %>
                <span>1</span>
                <br>
                <span>answer</span>
              <% end %>
            </li>
            <li class="page-item">
              <%= link_to question_path(question), class: "page-link", style: "font-size: 10px; text-align: center;" do %>
                <span>1</span>
                <br>
                <span>views</span>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col-12">
            <%= link_to question.title, question_path(question) %>
          </div>
        </div>
        <div class="row">
          <div class="col-7">
            <%= link_to 'tag', '', class: "badge badge-light" %>
            <%= link_to 'tag', '', class: "badge badge-light" %>
            <%= link_to 'tag', '', class: "badge badge-light" %>
            <%= link_to 'tag', '', class: "badge badge-light" %>
            <%= link_to 'tag', '', class: "badge badge-light" %>
            <%= link_to 'tag', '', class: "badge badge-light" %>
          </div>
          <div class="col-5">
            <%= question.created_before  %>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% cache @question do %>
  <div class="question">
    <%= render 'question' %>
    <div class="comments">
      <%= render 'comments/comments', parent: @question %>
    </div>
  </div>
  <hr>
  <div class="answers">
    <%= render 'answers' %>
  </div>
  <%= form_with(model: [@question, @answer], data: { type: :script }, class: 'new_answer' ) do |form| %>
    <div class="row">
      <div class="col-12">
        <%= form.label :body, 'Your answer' %>
        <div class="answer-errors">
        </div>
        <div>
          <%= form.text_area :body, cols: 83, rows: 10 %>
        </div>
        <div>
          <%= link_to_add_association 'Add file', form, :attachments, partial: 'questions/attachment_fields' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= current_user ? form.submit : link_to('Sign in to answer the question', new_user_session_path) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.question').html('<%= j render 'question' %>');
  $('.edit_question_link').click(function (e) {
    e.preventDefault();

    if (!$(this).hasClass('cancel')) {
      $(this).html('Cancel');
      $(this).addClass('cancel');
    } else {
      $(this).html('Edit');
      $(this).removeClass('cancel');
    };

    $('.edit_question').toggle();
  });
<% end %>